apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-redis
spec:
  replicas: 2
  selector:
    sb-instanceid-redis: redis
  template:
    metadata:
      labels:
        sb-instanceid-redis: redis
        servicebroker: sb-instanceid-redis
    spec:
      containers:
      - name: redis
        image: 172.30.188.59:5000/service-broker/redis-openshift-orchestration
        env:
          - name: SENTINEL_HOST
            value: sb-instanceid-redis
          - name: SENTINEL_PORT
            value: "26379"
          - name: REDIS_PASSWORD
            value: test1234
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}

