apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-redis-sentinel
spec:
  replicas: 2
  selector:
    sb-instanceid-sentinel: sentinel
  template:
    metadata:
      labels:
        sb-instanceid-sentinel: sentinel
        servicebroker: sb-instanceid-redis
    spec:
      containers:
      - name: sentinel
        image: 172.30.188.59:5000/service-broker/redis-openshift-orchestration
        env:
          - name: SENTINEL
            value: "true"
          - name: SENTINEL_HOST
            value: sb-instanceid-redis
          - name: SENTINEL_PORT
            value: "26379"
        ports:
          - containerPort: 26379
